In [3]:
import numpy as np

### Basic Operations

In [6]:
x = np.array([1,4,1,5,2,3,6,7,], dtype = 'int64')

In [8]:
print(x)

[1 4 1 5 2 3 6 7]


In [9]:
x

array([1, 4, 1, 5, 2, 3, 6, 7], dtype=int64)

In [14]:
# 2d array
y = np.array([[1,2,1,4,5,6,8,7,],[1,5,4,7,8,9,2,6]])
print(y)

[[1 2 1 4 5 6 8 7]
 [1 5 4 7 8 9 2 6]]


In [15]:
y

array([[1, 2, 1, 4, 5, 6, 8, 7],
       [1, 5, 4, 7, 8, 9, 2, 6]])

In [16]:
x.dtype

dtype('int64')

In [17]:
y.dtype

dtype('int32')

In [18]:
x.shape

(8,)

In [19]:
x.ndim

1

In [20]:
x.itemsize

8

In [22]:
x.nbytes

64

In [23]:
y.shape

(2, 8)

In [24]:
y.itemsize

4

In [25]:
y.ndim

2

In [26]:
y.nbytes

64

In [27]:
x.size

8

In [28]:
y.size

16

In [29]:
print(x.astype('float'))

[1. 4. 1. 5. 2. 3. 6. 7.]


In [30]:
print(x.astype('str'))

['1' '4' '1' '5' '2' '3' '6' '7']


In [31]:
# 3d array
z = np.array([[[1,2,5,3],[4,5,7,6],[7,9,6,5]]])
z

array([[[1, 2, 5, 3],
        [4, 5, 7, 6],
        [7, 9, 6, 5]]])

In [32]:
z.shape

(1, 3, 4)

In [34]:
z.size

12

In [39]:
print('dimensions:',z.ndim,'itemsize:',z.itemsize,'Total Size:',z.nbytes)

dimensions: 3 itemsize: 4 Total Size: 48


#### Accessing data

In [40]:
y

array([[1, 2, 1, 4, 5, 6, 8, 7],
       [1, 5, 4, 7, 8, 9, 2, 6]])

In [42]:
y[0,6]

8

In [43]:
y[:,4]

array([5, 8])

In [44]:
y[0,:]

array([1, 2, 1, 4, 5, 6, 8, 7])

In [45]:
y[0,0]

1

In [46]:
y[1,0:5]

array([1, 5, 4, 7, 8])

In [47]:
y[0,:-2]

array([1, 2, 1, 4, 5, 6])

In [48]:
z

array([[[1, 2, 5, 3],
        [4, 5, 7, 6],
        [7, 9, 6, 5]]])

In [49]:
z[::,-1]

array([[7, 9, 6, 5]])

In [50]:
z[0:,1,3]

array([6])

In [53]:
z[:,2,0:2]

array([[7, 9]])

In [57]:
z[0,0,0]

1

In [60]:
w = np.array([[[1,2],[2,3]],[[7,3],[4,6]]])

In [61]:
w

array([[[1, 2],
        [2, 3]],

       [[7, 3],
        [4, 6]]])

In [63]:
w[1,1,1]

6

In [65]:
y

array([[1, 2, 1, 4, 5, 6, 8, 7],
       [1, 5, 4, 7, 8, 9, 2, 6]])

In [66]:
y[0,2]= 15
y

array([[ 1,  2, 15,  4,  5,  6,  8,  7],
       [ 1,  5,  4,  7,  8,  9,  2,  6]])

In [67]:
y[0][7]

7

### Creating different arrays using numpy's inbuilt funcs

In [74]:
np.zeros((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [75]:
np.ones((4,6,9))

array([[[1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.,

In [76]:
np.full((4,6),46)

array([[46, 46, 46, 46, 46, 46],
       [46, 46, 46, 46, 46, 46],
       [46, 46, 46, 46, 46, 46],
       [46, 46, 46, 46, 46, 46]])

In [77]:
np.full_like(z, 3)

array([[[3, 3, 3, 3],
        [3, 3, 3, 3],
        [3, 3, 3, 3]]])

In [79]:
np.tile(z,2)

array([[[1, 2, 5, 3, 1, 2, 5, 3],
        [4, 5, 7, 6, 4, 5, 7, 6],
        [7, 9, 6, 5, 7, 9, 6, 5]]])

In [80]:
np.repeat(z,3)

array([1, 1, 1, 2, 2, 2, 5, 5, 5, 3, 3, 3, 4, 4, 4, 5, 5, 5, 7, 7, 7, 6,
       6, 6, 7, 7, 7, 9, 9, 9, 6, 6, 6, 5, 5, 5])

In [81]:
np.random.rand(3,4)

array([[0.16384791, 0.13372547, 0.17865307, 0.46141594],
       [0.74260453, 0.85953799, 0.71402492, 0.52805601],
       [0.71725508, 0.5796864 , 0.61327689, 0.52814212]])

In [82]:
np.random.randn(4,6)

array([[-0.69207548, -0.92713239,  0.46630044, -0.7921551 ,  2.15613658,
        -0.05767088],
       [ 0.03550469,  1.63403944, -0.78527864, -2.87197106,  1.48481473,
        -0.38581714],
       [-1.36002739,  0.32390272,  0.30579333,  0.80945547,  0.51759614,
         0.79968819],
       [ 0.66133577, -0.21278151,  0.44099507, -1.64582692,  0.19119925,
         0.06843863]])

In [87]:
a = np.random.randint(-4,6, size =(3,4))

In [88]:
a

array([[ 0, -2, -3,  3],
       [ 3,  1,  3, -3],
       [ 5, -4,  0,  0]])

In [89]:
np.identity(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [90]:
arr = np.array([[1,2,3,4,5]])

In [98]:
q = np.repeat(arr,3,axis = 0)

In [99]:
print(q)

[1 1 1 2 2 2 3 3 3 4 4 4 5 5 5]


### Mathematics

In [101]:
arr

array([1, 2, 3, 4, 5])

In [102]:
arr + 2

array([3, 4, 5, 6, 7])

In [105]:
arr -1

array([0, 1, 2, 3, 4])

In [107]:
arr*3

array([ 3,  6,  9, 12, 15])

In [108]:
arr/4

array([0.25, 0.5 , 0.75, 1.  , 1.25])

In [109]:
arr**4

array([  1,  16,  81, 256, 625], dtype=int32)

In [110]:
np.cos(arr)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219])

In [111]:
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [114]:
# matrix prod
u = np.full((2,8),3)
print(u)

v = np.random.rand(8,2)
print(v)

np.matmul(u,v)

[[3 3 3 3 3 3 3 3]
 [3 3 3 3 3 3 3 3]]
[[0.01733285 0.72064326]
 [0.89665242 0.74425353]
 [0.62634649 0.30102468]
 [0.88343512 0.32196068]
 [0.43697769 0.94004352]
 [0.12783897 0.926809  ]
 [0.50771522 0.79447206]
 [0.25359501 0.12589421]]


array([[11.24968134, 14.62530284],
       [11.24968134, 14.62530284]])

### Statistics

In [117]:
arr

array([1, 2, 3, 4, 5])

In [118]:
arr.mean()

3.0

In [119]:
arr.min()

1

In [121]:
arr.std()

1.4142135623730951

In [123]:
arr.max()

5

In [124]:
arr.var()

2.0

In [125]:
arr.squeeze()

array([1, 2, 3, 4, 5])

In [126]:
arr.flatten()

array([1, 2, 3, 4, 5])

In [129]:
arr.ravel()

array([1, 2, 3, 4, 5])

### array reshaping and stacking

In [130]:
y

array([[ 1,  2, 15,  4,  5,  6,  8,  7],
       [ 1,  5,  4,  7,  8,  9,  2,  6]])

In [131]:
y.shape

(2, 8)

In [132]:
y.reshape(8,2)

array([[ 1,  2],
       [15,  4],
       [ 5,  6],
       [ 8,  7],
       [ 1,  5],
       [ 4,  7],
       [ 8,  9],
       [ 2,  6]])

In [134]:
y.reshape(1,16)

array([[ 1,  2, 15,  4,  5,  6,  8,  7,  1,  5,  4,  7,  8,  9,  2,  6]])

In [136]:
y.reshape(4,4)

array([[ 1,  2, 15,  4],
       [ 5,  6,  8,  7],
       [ 1,  5,  4,  7],
       [ 8,  9,  2,  6]])

In [140]:
# vertically stacking
a = np.ones((1,8))
d = np.zeros((1,8))

np.vstack([a,d,a,d,a])

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [141]:
# horizontal stacking
n = np.ones((2,5))

In [142]:
m = np.zeros((2,9))

In [143]:
np.hstack([n,m])

array([[1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

### Loading file

In [147]:
file = np.genfromtxt('data.txt',delimiter=',')
file = file.astype('int64')
file


array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]], dtype=int64)

In [148]:
file[file>50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88], dtype=int64)

In [149]:
file[(file>=100)]

array([196, 766, 999], dtype=int64)

In [150]:
file[(file<100) | (file>900)]

array([  1,  13,  21,  11,  75,   4,   3,  34,   6,   7,   8,   0,   1,
         2,   3,   4,   5,   3,  42,  12,  33,  75,   4,  55,   6,   4,
         3,   4,   5,   6,   7,   0,  11,  12,   1,  22,  33,  11, 999,
        11,   2,   1,  78,   0,   1,   2,   9,   8,   7,   1,  76,  88],
      dtype=int64)

In [152]:
file[file == 1]

array([1, 1, 1, 1, 1, 1], dtype=int64)